import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import pg from 'pg';
import {migrateDatabase} from '../services/database.js';
import {createCommercialAccess,createPostgresAccessRepository} from '../services/commercialAccess.js';
import {createImageHistory} from '../services/imageHistory.js';
import {createStoreLock} from '../services/storeLock.js';
import {createStoreRedactor} from '../services/storeData.js';
import {createPurchaseRepository} from '../services/purchase.js';

test('real PostgreSQL: migration, one concurrent reservation, history persistence and store redaction', {skip:process.env.RUN_POSTGRES_TESTS!=='true'},async()=>{
  assert.ok(process.env.DATABASE_URL,'DATABASE_URL required');
  const schema='imagem_validation_'+crypto.randomBytes(8).toString('hex');
  assert.match(schema,/^imagem_validation_[a-f0-9]{16}$/);
  const connection=new URL(process.env.DATABASE_URL);
  if(connection.hostname.endsWith('.neon.tech'))connection.hostname=connection.hostname.replace('-pooler.','.');
  connection.searchParams.set('sslmode','verify-full');
  const config={connectionString:connection.href,ssl:{rejectUnauthorized:true},max:8};
  const admin=new pg.Pool(config);let pool;
  try {
    await admin.query(`create schema ${schema}`);
    pool=new pg.Pool({...config,options:`-c search_path=${schema}`});
    await pool.query('create table image_sync_access(store_id text primary key,demo_used_at timestamptz,paid_at timestamptz,payment_reference text unique)');
    await pool.query("insert into image_sync_access(store_id,demo_used_at) values('legacy-store',now())");
    await migrateDatabase(pool);await migrateDatabase(pool);
    assert.equal((await pool.query("select demo_batches_used from image_sync_access where store_id='legacy-store'")).rows[0].demo_batches_used,1);
    await pool.query("insert into stores(store_id,access_token) values('123','fake-validation-token'),('456','unrelated-validation-token')");
    const repository=createPostgresAccessRepository(()=>pool,async()=>{}),access=createCommercialAccess(repository);
    await access.authorize('123',['1'],{dryRun:true});assert.equal((await access.status('123')).demoBatchesUsed,0);
    const attempts=await Promise.allSettled(Array.from({length:20},()=>access.authorize('123',['1'])));
    assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);
    assert.equal((await access.status('123')).demoBatchesUsed,1);
    const purchases=createPurchaseRepository(()=>pool,async()=>{});
    const purchaseClaims=await Promise.all(Array.from({length:20},()=>purchases.claim('123')));
    assert.equal(purchaseClaims.filter(Boolean).length,1);
    assert.equal(await purchases.claim('456'),false);
    await purchases.save('validation-charge','123');
    assert.deepEqual(await purchases.get('123'),{status:'pending',chargeId:'validation-charge'});
    const reconnected=createCommercialAccess(createPostgresAccessRepository(()=>pool,async()=>{}));
    await assert.rejects(()=>reconnected.authorize('123',['1']),error=>error.status===402);
    const locks=createStoreLock(()=>pool,async()=>{}),release=await locks('123');
    await assert.rejects(()=>locks('123'),error=>error.status===409);await release();const nextRelease=await locks('123');await nextRelease();
    const history=createImageHistory(()=>pool,async()=>{}),state={skus:{'product:1':{productId:1,files:{'foto.png':{hash:'validation-hash',imageId:2}}}}};
    await history.save('123',state);
    assert.deepEqual(await createImageHistory(()=>pool,async()=>{}).load('123'),state);
    assert.deepEqual(await history.load('456'),{skus:{}});
    await pool.query("update image_sync_access set paid_at=now(),payment_reference='validation-paid' where store_id='123'");
    await reconnected.authorize('123',['1']);assert.equal((await reconnected.status('123')).demoBatchesUsed,1);
    const cleaned=[];
    await createStoreRedactor(()=>pool,async()=>{},locks,async id=>cleaned.push(id))('123');
    await createStoreRedactor(()=>pool,async()=>{},locks,async()=>{})('123');
    for(const table of ['stores','image_sync_access','image_sync_history','image_sync_purchase'])assert.equal((await pool.query(`select count(*)::int as count from ${table} where store_id='123'`)).rows[0].count,0);
    assert.equal((await pool.query("select count(*)::int as count from stores where store_id='456'")).rows[0].count,1);
    assert.deepEqual(cleaned,['123']);await assert.rejects(()=>history.save('123',state),/store_no_longer_authorized/);
  }finally {
    if(pool)await pool.end();
    // Only the schema generated by this test, containing invented validation data.
    assert.match(schema,/^imagem_validation_[a-f0-9]{16}$/);
    await admin.query(`drop schema if exists ${schema} cascade`);await admin.end();
  }
});
